version: '3.8'

name: sharding-repl-cache

services:
  # Config Server Replica Set
  configdb:
    image: mongo:latest
    container_name: configdb
    command: mongod --configsvr --replSet configrs --port 27019 --bind_ip_all
    volumes:
      - configdb_data:/data/db

  # Shard 1 - Replica Set (3 узла)
  shard1a:
    image: mongo:latest
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    volumes:
      - shard1a_data:/data/db

  shard1b:
    image: mongo:latest
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    volumes:
      - shard1b_data:/data/db

  shard1c:
    image: mongo:latest
    container_name: shard1c
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    volumes:
      - shard1c_data:/data/db

  # Shard 2 - Replica Set (3 узла)
  shard2a:
    image: mongo:latest
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2rs --port 27018 --bind_ip_all
    volumes:
      - shard2a_data:/data/db

  shard2b:
    image: mongo:latest
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2rs --port 27018 --bind_ip_all
    volumes:
      - shard2b_data:/data/db

  shard2c:
    image: mongo:latest
    container_name: shard2c
    command: mongod --shardsvr --replSet shard2rs --port 27018 --bind_ip_all
    volumes:
      - shard2c_data:/data/db

  # Mongos (Query Router)
  mongos:
    image: mongo:latest
    container_name: mongos
    command: mongos --configdb configrs/configdb:27019 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    depends_on:
      - configdb
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c

  # Redis (Новый сервис для кеширования)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Проброс порта Redis для возможного внешнего доступа/дебага
    volumes:
      - redis_data:/data # Для сохранения данных Redis

  # API приложение (теперь использует Redis)
  pymongo_api:
    container_name: pymongo_api
    build:
      context: ../api_app # Путь к папке с Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379" # !!! Включаем кеширование, указывая URL Redis !!!
    depends_on:
      - mongos
      - redis # !!! Теперь API зависит от Redis !!!

volumes:
  configdb_data:
  shard1a_data:
  shard1b_data:
  shard1c_data:
  shard2a_data:
  shard2b_data:
  shard2c_data:
  redis_data: # Новый том для данных Redis
